// <auto-generated />
using System;
using FormationAI.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormationAI.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormationAI.API.Models.AvatarVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormationId")
                        .HasColumnType("integer");

                    b.Property<string>("HeyGenVideoId")
                        .HasColumnType("text");

                    b.Property<string>("ScriptTexte")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("AvatarVideos");
                });

            modelBuilder.Entity("FormationAI.API.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FormationAI.API.Models.Certificat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateEmission")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormationId")
                        .HasColumnType("integer");

                    b.Property<double>("Note")
                        .HasColumnType("double precision");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprenantId");

                    b.HasIndex("FormationId");

                    b.ToTable("Certificats");
                });

            modelBuilder.Entity("FormationAI.API.Models.Contenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvatarVideoId")
                        .HasColumnType("integer");

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<int>("Modalite")
                        .HasColumnType("integer");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<int?>("QuizId")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarVideoId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("QuizId");

                    b.ToTable("Contenus");
                });

            modelBuilder.Entity("FormationAI.API.Models.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategorieId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DureeHeures")
                        .HasColumnType("integer");

                    b.Property<int>("FormateurId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Prix")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("Publiee")
                        .HasColumnType("boolean");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("FormateurId");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("FormationAI.API.Models.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SessionFormationId")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionFormationId");

                    b.HasIndex("ApprenantId", "SessionFormationId")
                        .IsUnique();

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("FormationAI.API.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FormationId")
                        .HasColumnType("integer");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("FormationAI.API.Models.Progression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DerniereMiseAJour")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DerniereNote")
                        .HasColumnType("double precision");

                    b.Property<int>("InscriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("Pourcentage")
                        .HasColumnType("integer");

                    b.Property<bool>("Termine")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("InscriptionId")
                        .IsUnique();

                    b.ToTable("Progressions");
                });

            modelBuilder.Entity("FormationAI.API.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Enonce")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("FormationAI.API.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FormationId")
                        .HasColumnType("integer");

                    b.Property<int>("NoteMinimale")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("FormationAI.API.Models.Reponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstCorrecte")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Reponses");
                });

            modelBuilder.Entity("FormationAI.API.Models.SessionFormation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormationId")
                        .HasColumnType("integer");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PlacesMax")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("FormationAI.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FormationAI.API.Models.AvatarVideo", b =>
                {
                    b.HasOne("FormationAI.API.Models.Formation", "Formation")
                        .WithMany("AvatarVideos")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("FormationAI.API.Models.Certificat", b =>
                {
                    b.HasOne("FormationAI.API.Models.User", "Apprenant")
                        .WithMany("Certificats")
                        .HasForeignKey("ApprenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormationAI.API.Models.Formation", "Formation")
                        .WithMany()
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apprenant");

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("FormationAI.API.Models.Contenu", b =>
                {
                    b.HasOne("FormationAI.API.Models.AvatarVideo", "AvatarVideo")
                        .WithMany()
                        .HasForeignKey("AvatarVideoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FormationAI.API.Models.Module", "Module")
                        .WithMany("Contenus")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormationAI.API.Models.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AvatarVideo");

                    b.Navigation("Module");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("FormationAI.API.Models.Formation", b =>
                {
                    b.HasOne("FormationAI.API.Models.Categorie", "Categorie")
                        .WithMany("Formations")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FormationAI.API.Models.User", "Formateur")
                        .WithMany("FormationsAnimees")
                        .HasForeignKey("FormateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Formateur");
                });

            modelBuilder.Entity("FormationAI.API.Models.Inscription", b =>
                {
                    b.HasOne("FormationAI.API.Models.User", "Apprenant")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ApprenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FormationAI.API.Models.SessionFormation", "SessionFormation")
                        .WithMany("Inscriptions")
                        .HasForeignKey("SessionFormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apprenant");

                    b.Navigation("SessionFormation");
                });

            modelBuilder.Entity("FormationAI.API.Models.Module", b =>
                {
                    b.HasOne("FormationAI.API.Models.Formation", "Formation")
                        .WithMany("Modules")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("FormationAI.API.Models.Progression", b =>
                {
                    b.HasOne("FormationAI.API.Models.Inscription", "Inscription")
                        .WithOne("Progression")
                        .HasForeignKey("FormationAI.API.Models.Progression", "InscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscription");
                });

            modelBuilder.Entity("FormationAI.API.Models.Question", b =>
                {
                    b.HasOne("FormationAI.API.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("FormationAI.API.Models.Quiz", b =>
                {
                    b.HasOne("FormationAI.API.Models.Formation", "Formation")
                        .WithMany("Quizzes")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("FormationAI.API.Models.Reponse", b =>
                {
                    b.HasOne("FormationAI.API.Models.Question", "Question")
                        .WithMany("Reponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("FormationAI.API.Models.SessionFormation", b =>
                {
                    b.HasOne("FormationAI.API.Models.Formation", "Formation")
                        .WithMany("Sessions")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("FormationAI.API.Models.Categorie", b =>
                {
                    b.Navigation("Formations");
                });

            modelBuilder.Entity("FormationAI.API.Models.Formation", b =>
                {
                    b.Navigation("AvatarVideos");

                    b.Navigation("Modules");

                    b.Navigation("Quizzes");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("FormationAI.API.Models.Inscription", b =>
                {
                    b.Navigation("Progression");
                });

            modelBuilder.Entity("FormationAI.API.Models.Module", b =>
                {
                    b.Navigation("Contenus");
                });

            modelBuilder.Entity("FormationAI.API.Models.Question", b =>
                {
                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("FormationAI.API.Models.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("FormationAI.API.Models.SessionFormation", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("FormationAI.API.Models.User", b =>
                {
                    b.Navigation("Certificats");

                    b.Navigation("FormationsAnimees");

                    b.Navigation("Inscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
